target 'MobileSales' do
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'UMengAnalytics'
pod 'FMDB'
pod 'CocoaAsyncSocket'
pod 'MBProgressHUD', '~> 1.0.0'
end
